version: '3.1'
services:
  php:
    build: .
    container_name: php_dev_image
    volumes:
      - "./:/var/www/html"
    ports:
      - 3000:80
      - 443:443
    networks:
      - php-network
  db:
    image: mysql:latest
    container_name: mysql_dev_image
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root@123
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
      - php-network
      
  adminer:
    image: adminer
    container_name: adminer_dev_image
    restart: always
    ports:
      - 3001:8080
    networks:
      - php-network

networks:
  php-network: